spring.application.name=mini-proj

spring.datasource.url=jdbc:postgresql://localhost:5432/miniproj
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false

# Swagger UI ??? ?? (??? ?? ?? ??)
springdoc.swagger-ui.path=/swagger-ui.html

# API ??? ? ?? ??? ?? (?? ??? ?? ??)
springdoc.packages-to-scan=com.co2ma.mini_proj

# ?? ??(Prod)??? Swagger ???? (??)
# springdoc.api-docs.enabled=false
# springdoc.swagger-ui.enabled=false

# ?? ?? ? ?? ?? (Bean ?? properties? ??)
springdoc.openapi.info.title=Mini Project API
springdoc.openapi.info.version=v1.0.0
springdoc.openapi.info.description=Swagger Test